# Generated by Django 5.0.7 on 2024-07-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatewayapi', '0005_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
