# Generated by Django 5.0.7 on 2024-07-26 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gatewayapi', '0006_testing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='media_url',
        ),
        migrations.RemoveField(
            model_name='message',
            name='message_id',
        ),
    ]
