# Generated by Django 5.0.7 on 2024-07-27 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatewayapi', '0009_message_from_jid_message_message_id_message_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='msisdns',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='customer',
            name='language',
            field=models.CharField(choices=[('nso_Latn', 'Northern Sotho'), ('afr_Latn', 'Afrikaans'), ('sot_Latn', 'Southern Sotho'), ('ssw_Latn', 'Swati'), ('tso_Latn', 'Tsonga'), ('tsn_Latn', 'Setswana'), ('xho_Latn', 'Xhosa'), ('zul_Latn', 'Zulu'), ('eng_Latn', 'English'), ('swh_Latn', 'Swahili')], default='eng_Latn', max_length=10),
        ),
    ]
